$primary_paletteKeyColor = a9673b
$secondary_paletteKeyColor = 90705d
$tertiary_paletteKeyColor = 7a7949
$neutral_paletteKeyColor = 81746d
$neutral_variant_paletteKeyColor = 85746b
$background = 19120d
$onBackground = f0dfd7
$surface = 19120d
$surfaceDim = 19120d
$surfaceBright = 413731
$surfaceContainerLowest = 140d08
$surfaceContainerLow = 221a15
$surfaceContainer = 261e19
$surfaceContainerHigh = 312823
$surfaceContainerHighest = 3d332d
$onSurface = f0dfd7
$surfaceVariant = 52443c
$onSurfaceVariant = d7c2b8
$inverseSurface = f0dfd7
$inverseOnSurface = 382e29
$outline = 9f8d83
$outlineVariant = 52443c
$shadow = 000000
$scrim = 000000
$surfaceTint = ffb689
$primary = ffb689
$onPrimary = 512300
$primaryContainer = 6e3810
$onPrimaryContainer = ffdbc8
$inversePrimary = 8b4f25
$secondary = e5bfa9
$onSecondary = 432b1c
$secondaryContainer = 5c4130
$onSecondaryContainer = ffdbc8
$tertiary = cbc992
$onTertiary = 323209
$tertiaryContainer = 949361
$onTertiaryContainer = 000000
$error = ffb4ab
$onError = 690005
$errorContainer = 93000a
$onErrorContainer = ffdad6
$primaryFixed = ffdbc8
$primaryFixedDim = ffb689
$onPrimaryFixed = 311300
$onPrimaryFixedVariant = 6e3810
$secondaryFixed = ffdbc8
$secondaryFixedDim = e5bfa9
$onSecondaryFixed = 2b1709
$onSecondaryFixedVariant = 5c4130
$tertiaryFixed = e7e5ac
$tertiaryFixedDim = cbc992
$onTertiaryFixed = 1d1d00
$onTertiaryFixedVariant = 49491e
$term0 = 353433
$term1 = ee6800
$term2 = ffbf83
$term3 = ffe0cb
$term4 = b9ab66
$term5 = f0926e
$term6 = fcbe71
$term7 = edd3c3
$term8 = b39f93
$term9 = ff8944
$term10 = ffd6b2
$term11 = fff2ea
$term12 = dbbc92
$term13 = ffab88
$term14 = ffd4a5
$term15 = ffffff
$rosewater = ffeee7
$flamingo = ffdaca
$pink = ffd3c6
$mauve = ffab99
$red = ff9a6e
$maroon = f8ad8c
$peach = ffc09a
$yellow = ffeee3
$green = ffd9b1
$teal = ffdb94
$sky = e1df87
$sapphire = b3d27e
$blue = ffa2bd
$lavender = ffbcbb
$klink = bf6ba0
$klinkSelection = bf6ba0
$kvisited = ce5f43
$kvisitedSelection = ce5f43
$knegative = e45e00
$knegativeSelection = e35f00
$kneutral = ff8c3b
$kneutralSelection = ff8c3b
$kpositive = ea9700
$kpositiveSelection = ea9700
$text = f0dfd7
$subtext1 = d7c2b8
$subtext0 = 9f8d83
$overlay2 = 8b7b71
$overlay1 = 76685f
$overlay0 = 64574f
$surface2 = 52463f
$surface1 = 40352f
$surface0 = 2c231e
$base = 19120d
$mantle = 19120d
$crust = 18110c
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
