# vim:ft=kitty

# Open URL
map --allow-fallback=shifted,ascii ctrl+shift+e open_url_with_hints

# Insert selected path
map --allow-fallback=shifted,ascii ctrl+shift+p>f kitten hints --type path --program -

# Open selected path
map --allow-fallback=shifted,ascii ctrl+shift+p>shift+f kitten hints --type path

# Insert chosen file
map --allow-fallback=shifted,ascii ctrl+shift+p>c kitten choose-files

# 一次选择多个文件
map --allow-fallback=shifted,ascii ctrl+shift+p>v kitten choose-files --mode=files

# Insert chosen directory
map --allow-fallback=shifted,ascii ctrl+shift+p>d kitten choose-files --mode=dir

# hash Insert selected line
map --allow-fallback=shifted,ascii ctrl+shift+p>l kitten hints --type line --program -

# Insert selected word
map --allow-fallback=shifted,ascii ctrl+shift+p>w kitten hints --type word --program -

# Insert selected hash
map --allow-fallback=shifted,ascii ctrl+shift+p>h kitten hints --type hash --program -

# Open the selected file at the selected line
map --allow-fallback=shifted,ascii ctrl+shift+p>n kitten hints --type linenum

# Open the selected hyperlink
map --allow-fallback=shifted,ascii ctrl+shift+p>y kitten hints --type hyperlink

# Open the selected file in a new tab inside neovim
map ctrl+g kitten hints --type=linenum --linenum-action=tab nvim +{line} {path}
