# vim:ft=kitty

# Open URL
map ctrl+shift+e open_url_with_hints

# Insert selected path
map ctrl+shift+p>f kitten hints --type path --program -

# Open selected path
map ctrl+shift+p>shift+f kitten hints --type path

#hash Insert selected line
map ctrl+shift+p>l kitten hints --type line --program -

# Insert selected word
map ctrl+shift+p>w kitten hints --type word --program -

# Insert selected hash
map ctrl+shift+p>h kitten hints --type hash --program -

# Open the selected file at the selected line
map ctrl+shift+p>n kitten hints --type linenum

# Open the selected hyperlink
map ctrl+shift+p>y kitten hints --type hyperlink

