# vim:ft=kitty
###################t
#####  鼠标  ######
####################
click_interval 0.5
mouse_hide_wait 3.0

pointer_shape_when_grabbed arrow
default_pointer_shape beam
pointer_shape_when_dragging beam

####################
###### url链接  ####
####################
# open_url_with chromium
# open_url_with zen
open_url_with qutebrowser
url_color #0087bd
url_style curly
# url_style straight
# url_style double
# url_style dotted
# url_style dashed
url_prefixes file ftp ftps gemini git gopher http https irc ircs kitty mailto news sftp ssh
# 鼠标经过url,显示下划线
underline_hyperlinks hover
show_hyperlink_targets yes
detect_urls yes
allow_hyperlinks yes

####################
####  复制黏贴 ####
####################
copy_on_select clipboard
paste_actions quote-urls-at-prompt,replace-newline,confirm
strip_trailing_spaces smart
select_by_word_characters @-._~?&=%+#
select_by_word_characters_forward @-./_~?&=%+#

# selection_foreground #000000
# selection_background #fffacd

####################
#####  回滚  ######
####################
scrollback_lines 8000
scrollback_pager less +G -R
wheel_scroll_multiplier 5.0

# 音频设置 - 禁用终端铃声（避免烦人的提示音）
enable_audio_bell no
