# vim:ft=kitty
####################
###### 窗口  #######
####################
enabled_layouts *
enabled_layouts stack
enabled_layouts grid
enabled_layouts tall:bias=50;full_size=1;mirrored=false
enabled_layouts fat:bias=50;full_size=1;mirrored=false
enabled_layouts splits:split_axis=horizontal
enabled_layouts vertical

remember_window_size   yes
initial_window_width   640
initial_window_height  400

draw_window_borders_for_single_window no
window_border_width 0.5pt
window_margin_width 8 3 3 5
# window_margin_width 8
single_window_margin_width -1

window_padding_width 8 8 0 8
# window_padding_width 15
single_window_padding_width -1

remember_window_position yes

window_resize_step_cells 2
window_resize_step_lines 2
placement_strategy top-left
visual_window_select_characters 1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ

hide_window_decorations yes
# hide_window_decorations titlebar-only
active_border_color #00ff00
# inactive_border_color #cccccc
bell_border_color #ff5a00

window_logo_path kitty.png
window_logo_position top-right
window_logo_alpha 0.2

window_title_bar bottom
window_title_bar_min_windows 0
