[manager]

keymap = [
	{ on = [ "<Esc>" ], exec = "escape",             desc = "退出visual模式, 清除选择, 取消搜索" },
	{ on = [ "q" ],     exec = "quit",               desc = "退出" },
	{ on = [ "Q" ],     exec = "quit --no-cwd-file", desc = "强制退出，不保存修改" },
	# { on = [ "<C-q>" ], exec = "close",              desc = "Close the current tab, or quit if it is last tab" },
	{ on = [ "<C-z>" ], exec = "suspend",            desc = "暂停" },

	# Navigation
	{ on = [ "k" ], exec = "arrow -1", desc = "向上移动一行" },
	{ on = [ "j" ], exec = "arrow 1",  desc = "向下移动一行" },

	{ on = [ "K" ], exec = "arrow -5", desc = "向上移动5行" },
	{ on = [ "J" ], exec = "arrow 5",  desc = "向下移动5行" },

	{ on = [ "<S-Up>" ],   exec = "arrow -5", desc = "向上移动5行" },
	{ on = [ "<S-Down>" ], exec = "arrow 5",  desc = "向下移动5行" },

	{ on = [ "<C-u>" ], exec = "arrow -50%",  desc = "向上移动半屏" },
	{ on = [ "<C-d>" ], exec = "arrow 50%",   desc = "向下移动半屏" },
	{ on = [ "<C-b>" ], exec = "arrow -100%", desc = "向上移动整屏" },
	{ on = [ "<C-f>" ], exec = "arrow 100%",  desc = "向下移动整屏" },

	{ on = [ "<C-PageUp>" ],   exec = "arrow -50%",  desc = "向上移动半屏" },
	{ on = [ "<C-PageDown>" ], exec = "arrow 50%",   desc = "向下移动半屏" },
	{ on = [ "<PageUp>" ],     exec = "arrow -100%", desc = "向上移动整屏" },
	{ on = [ "<PageDown>" ],   exec = "arrow 100%",  desc = "向下移动整屏" },

	{ on = [ "h" ], exec = [ "leave", "escape --visual --select" ], desc = "进入上层目录" },
	{ on = [ "l" ], exec = [ "enter", "escape --visual --select" ], desc = "进入子目录" },

	{ on = [ "H" ], exec = "back",    desc = "回退上一个目录" },
	{ on = [ "L" ], exec = "forward", desc = "进入下一个目录" },

	{ on = [ "<A-k>" ], exec = "seek -5", desc = "Seek up 5 units in the preview" },
	{ on = [ "<A-j>" ], exec = "seek 5",  desc = "Seek down 5 units in the preview" },
	{ on = [ "<A-PageUp>" ],   exec = "seek -5", desc = "Seek up 5 units in the preview" },
	{ on = [ "<A-PageDown>" ], exec = "seek 5",  desc = "Seek down 5 units in the preview" },

	{ on = [ "<Up>" ],    exec = "arrow -1", desc = "向上移动一行" },
	{ on = [ "<Down>" ],  exec = "arrow 1",  desc = "向下移动一行" },
	{ on = [ "<Left>" ],  exec = "leave",    desc = "进入上层目" },
	{ on = [ "<Right>" ], exec = "enter",    desc = "进入子目录" },

	{ on = [ "g", "g" ], exec = "arrow -99999999", desc = "移动到顶部" },
	{ on = [ "G" ],      exec = "arrow 99999999",  desc = "移动到底部" },

	# Selection
	{ on = [ "<Space>" ], exec = [ "select --state=none", "arrow 1" ], desc = "切换选择状态" },
	{ on = [ "v" ],       exec = "visual_mode",                        desc = "进入visual模式" },
	{ on = [ "V" ],       exec = "visual_mode --unset",                desc = "退出visual模式(unset mode)" },
	{ on = [ "<C-a>" ],   exec = "select_all --state=true",            desc = "全选" },
	{ on = [ "<C-r>" ],   exec = "select_all --state=none",            desc = "打开/取消全选" },

	# Operation
	{ on = [ "o" ],         exec = "open",                                                 desc = "打开选择的文件" },
	{ on = [ "O" ],         exec = "open --interactive",                                   desc = "交互式打开选择的文件" },
	{ on = [ "<Enter>" ],   exec = "open",                                                 desc = "打开选择的文件" },
	{ on = [ "<C-Enter>" ], exec = "open --interactive",                                   desc = "交互式打开选择的文件" },
	{ on = [ "y" ],         exec = [ "yank", "escape --visual --select" ],                 desc = "复制选择的文件" },
	{ on = [ "x" ],         exec = [ "yank --cut", "escape --visual --select" ],           desc = "剪切选择的文件" },
	{ on = [ "p" ],         exec = "paste",                                                desc = "粘贴选择的文件" },
	{ on = [ "P" ],         exec = "paste --force",                                        desc = "粘贴选择的文件(如果文件存在则覆盖文件)" },
	{ on = [ "-" ],         exec = "link",                                                 desc = "Symlink the absolute path of files" },
	{ on = [ "_" ],         exec = "link --relative",                                      desc = "Symlink the relative path of files" },
	{ on = [ "d" ],         exec = [ "remove", "escape --visual --select" ],               desc = "移动到回收站" },
	{ on = [ "D" ],         exec = [ "remove --permanently", "escape --visual --select" ], desc = "永久删除" },
	{ on = [ "a" ],         exec = "create",                                               desc = "新建文件或目录(新建目录需要以/结尾)" },
	{ on = [ "r" ],         exec = "rename",                                               desc = "重命名文件或目录" },
	{ on = [ ";" ],         exec = "shell",                                                desc = "运行shell命令" },
	{ on = [ ":" ],         exec = "shell --block",                                        desc = "运行shell命令(冻结UI直到命令完成)" },
	{ on = [ "." ],         exec = "hidden toggle",                                        desc = "显示隐藏文件" },
	{ on = [ "s" ],         exec = "search fd",                                            desc = "名字搜索，使用fd做后端" },
	{ on = [ "S" ],         exec = "search rg",                                            desc = "搜索文件内容, 使用ripgrep做后端" },
	{ on = [ "<C-s>" ],     exec = "search none",                                          desc = "取消正在进行的搜索" },
	{ on = [ "z" ],         exec = "jump zoxide",                                          desc = "切换目录, 使用zoxide做后端" },
	{ on = [ "Z" ],         exec = "jump fzf",                                             desc = "切换目录或定位文件, 使用fzf做后端" },

	# Linemode
	{ on = [ "m", "s" ], exec = "linemode size",        desc = "Set linemode to size" },
	{ on = [ "m", "p" ], exec = "linemode permissions", desc = "Set linemode to permissions" },
	{ on = [ "m", "m" ], exec = "linemode mtime",       desc = "Set linemode to mtime" },
	{ on = [ "m", "n" ], exec = "linemode none",        desc = "Set linemode to none" },

	# Copy
	{ on = [ "c", "c" ], exec = "copy path",             desc = "复制绝对路径" },
	{ on = [ "c", "d" ], exec = "copy dirname",          desc = "复制父目录路径" },
	{ on = [ "c", "f" ], exec = "copy filename",         desc = "复制文件名" },
	{ on = [ "c", "n" ], exec = "copy name_without_ext", desc = "复制文件名, 不包括扩展名" },

	# Filter
	{ on = [ "f" ], exec = "filter --smart", desc = "过滤文件" },

	# Find
	{ on = [ "/" ], exec = "find --smart",            desc = "向前搜索文件" },
	{ on = [ "?" ], exec = "find --previous --smart", desc = "向后搜索文件" },
	{ on = [ "n" ], exec = "find_arrow",              desc = "搜索下一个" },
	{ on = [ "N" ], exec = "find_arrow --previous",   desc = "搜索上一个" },

	# Sorting
	{ on = [ ",", "m" ], exec = "sort modified --dir-first",               desc = "按修改时间排序" },
	{ on = [ ",", "M" ], exec = "sort modified --reverse --dir-first",     desc = "按修改时间排序(降序)" },
	{ on = [ ",", "c" ], exec = "sort created --dir-first",                desc = "按创建时间排序" },
	{ on = [ ",", "C" ], exec = "sort created --reverse --dir-first",      desc = "按创建时间排序(降序)" },
	{ on = [ ",", "e" ], exec = "sort extension --dir-first",         	   desc = "按扩展名排序" },
	{ on = [ ",", "E" ], exec = "sort extension --reverse --dir-first",    desc = "按扩展名排序(降序)" },
	{ on = [ ",", "a" ], exec = "sort alphabetical --dir-first",           desc = "按字母排序" },
	{ on = [ ",", "A" ], exec = "sort alphabetical --reverse --dir-first", desc = "按字母排序(降序)" },
	{ on = [ ",", "n" ], exec = "sort natural --dir-first",                desc = "自然排序" },
	{ on = [ ",", "N" ], exec = "sort natural --reverse --dir-first",      desc = "自然排序(降序)" },
	{ on = [ ",", "s" ], exec = "sort size --dir-first",                   desc = "按文件大小排序" },
	{ on = [ ",", "S" ], exec = "sort size --reverse --dir-first",         desc = "按文件大小排序 (降序)" },

	# Tabs
	{ on = [ "t" ], exec = "tab_create --current", desc = "新建标签" },

	{ on = [ "1" ], exec = "tab_switch 0", desc = "切换到第1个标签" },
	{ on = [ "2" ], exec = "tab_switch 1", desc = "切换到第2个标签" },
	{ on = [ "3" ], exec = "tab_switch 2", desc = "切换到第3个标签" },
	{ on = [ "4" ], exec = "tab_switch 3", desc = "切换到第4个标签" },
	{ on = [ "5" ], exec = "tab_switch 4", desc = "切换到第5个标签" },
	{ on = [ "6" ], exec = "tab_switch 5", desc = "切换到第6个标签" },
	{ on = [ "7" ], exec = "tab_switch 6", desc = "切换到第7个标签" },
	{ on = [ "8" ], exec = "tab_switch 7", desc = "切换到第8个标签" },
	{ on = [ "9" ], exec = "tab_switch 8", desc = "切换到第9个标签" },

	{ on = [ "[" ], exec = "tab_switch -1 --relative", desc = "切换到前一个标签" },
	{ on = [ "]" ], exec = "tab_switch 1 --relative",  desc = "切换到下一个个标签" },

	{ on = [ "{" ], exec = "tab_swap -1", desc = "与前一个标签交换位置" },
	{ on = [ "}" ], exec = "tab_swap 1",  desc = "与后一个标签交换位置" },

	# Tasks
	{ on = [ "w" ], exec = "tasks_show", desc = "显示任务管理器" },

	# Goto
	{ on = [ "g", "c" ],       exec = "cd ~/.config",     desc = "进入config目录" },
	{ on = [ "g", "d" ],       exec = "cd ~/下载",		  desc = "进入下载目录" },
	{ on = [ "g", "D" ],       exec = "cd ~/文档",		  desc = "进入文档目录" },
	{ on = [ "g", "e" ],       exec = "cd ~/桌面",		  desc = "进入桌面目录" },
	{ on = [ "g", "h" ],       exec = "cd ~",             desc = "进入HOME目录" },
	{ on = [ "g", "M" ],       exec = "cd ~/音乐",		  desc = "进入音乐目录" },
	{ on = [ "g", "m" ],       exec = "cd /media/数据/音乐/",		  desc = "进入音乐目录" },
	{ on = [ "g", "p" ],       exec = "cd ~/图片",		  desc = "进入图片目录" },
	{ on = [ "g", "s" ],       exec = "cd ~/.dotfiles",     desc = "进入config目录" },
	{ on = [ "g", "t" ],       exec = "cd /tmp",          desc = "进入tmp目录" },
	{ on = [ "g", "v" ],       exec = "cd ~/视频",		  desc = "进入视频目录" },
	{ on = [ "g", "w" ],       exec = "cd ~/图片/Wallpapers",          desc = "进入壁纸目录" },
	{ on = [ "g", "<Space>" ], exec = "cd --interactive", desc = "请输入想要进入的目录" },

	# Help
	{ on = [ "~" ], exec = "help", desc = "打开帮助" },
]

[tasks]

keymap = [
	{ on = [ "<Esc>" ], exec = "close", desc = "隐藏任务管理器" },
	{ on = [ "<C-q>" ], exec = "close", desc = "隐藏任务管理器" },
	{ on = [ "w" ],     exec = "close", desc = "隐藏任务管理器" },

	{ on = [ "k" ], exec = "arrow -1", desc = "向上移动一行" },
	{ on = [ "j" ], exec = "arrow 1",  desc = "向下移动一行" },

	{ on = [ "<Up>" ],   exec = "arrow -1", desc = "向上移动一行" },
	{ on = [ "<Down>" ], exec = "arrow 1",  desc = "向下移动一行" },

	{ on = [ "<Enter>" ], exec = "inspect", desc = "检查任务" },
	{ on = [ "x" ],       exec = "cancel",  desc = "取消任务" },

	{ on = [ "~" ], exec = "help", desc = "打开帮助" }
]

[select]

keymap = [
	{ on = [ "<C-q>" ],   exec = "close",          desc = "取消选择" },
	{ on = [ "<Esc>" ],   exec = "close",          desc = "取消选择" },
	{ on = [ "<Enter>" ], exec = "close --submit", desc = "提交选择" },

	{ on = [ "k" ], exec = "arrow -1", desc = "向上移动一行" },
	{ on = [ "j" ], exec = "arrow 1",  desc = "向下移动一行" },

	{ on = [ "K" ], exec = "arrow -5", desc = "向上移动五行" },
	{ on = [ "J" ], exec = "arrow 5",  desc = "向下移动五行" },

	{ on = [ "<Up>" ],   exec = "arrow -1", desc = "向上移动一行" },
	{ on = [ "<Down>" ], exec = "arrow 1",  desc = "向下移动一行" },
                                                                
	{ on = [ "<S-Up>" ],   exec = "arrow -5", desc ="向上移动五行" },
	{ on = [ "<S-Down>" ], exec = "arrow 5",  desc ="向下移动五行" },

	{ on = [ "~" ], exec = "help", desc = "打开帮助" }
]

[input]

keymap = [
	{ on = [ "<C-q>" ],   exec = "close",          desc = "取消输入" },
	{ on = [ "<Enter>" ], exec = "close --submit", desc = "提交输入" },
	{ on = [ "<Esc>" ],   exec = "escape",         desc = "回退normal模式, 或者取消输入" },

	# Mode
	{ on = [ "i" ], exec = "insert",                              desc = "进入insert模式" },
	{ on = [ "a" ], exec = "insert --append",                     desc = "进入append模式" },
	{ on = [ "I" ], exec = [ "move -999", "insert" ],             desc = "进入insert模式, 并移动到文件顶部" },
	{ on = [ "A" ], exec = [ "move 999", "insert --append" ],     desc = "进入append模式, 并移动到文件底部" },
	{ on = [ "v" ], exec = "visual",                              desc = "进入visual模式" },
	{ on = [ "V" ], exec = [ "move -999", "visual", "move 999" ], desc = "进入visual模式并全选" },

	# Character-wise movement
	{ on = [ "h" ],       exec = "move -1", desc = "向后移动一个字符" },
	{ on = [ "l" ],       exec = "move 1",  desc = "向前移动一个字符" },
	{ on = [ "<Left>" ],  exec = "move -1", desc = "向后移动一个字符" },
	{ on = [ "<Right>" ], exec = "move 1",  desc = "向前移动一个字符" },
	{ on = [ "<C-b>" ],   exec = "move -1", desc = "向后移动一个字符" },
	{ on = [ "<C-f>" ],   exec = "move 1",  desc = "向前移动一个字符" },

	# Word-wise movement
	{ on = [ "b" ],     exec = "backward",              desc = "向后移动一个单词" },
	{ on = [ "w" ],     exec = "forward",               desc = "向前移动一个单词" },
	{ on = [ "e" ],     exec = "forward --end-of-word", desc = "向前移动一个单词" },
	{ on = [ "<A-b>" ], exec = "backward",              desc = "向后移动一个单词" },
	{ on = [ "<A-f>" ], exec = "forward --end-of-word", desc = "向前移动一个单词" },

	# Line-wise movement
	{ on = [ "0" ],     exec = "move -999", desc = "移动到行首" },
	{ on = [ "$" ],     exec = "move 999",  desc = "移动到行尾" },
	{ on = [ "<C-a>" ], exec = "move -999", desc = "移动到行首" },
	{ on = [ "<C-e>" ], exec = "move 999",  desc = "移动到行尾" },

	# Delete
	{ on = [ "<Backspace>" ], exec = "backspace",	        desc = "向后删除一个字符" },
	{ on = [ "<C-h>" ],       exec = "backspace",         desc = "向后删除一个字符" },
	{ on = [ "<C-d>" ],       exec = "backspace --under", desc = "删除光标处字符" },

	# Kill
	{ on = [ "<C-u>" ], exec = "kill bol",      desc = "Kill backwards to the BOL" },
	{ on = [ "<C-k>" ], exec = "kill eol",      desc = "Kill forwards to the EOL" },
	{ on = [ "<C-w>" ], exec = "kill backward", desc = "Kill backwards to the start of the current word" },
	{ on = [ "<A-d>" ], exec = "kill forward",  desc = "Kill forwards to the end of the current word" },

	# Cut/Yank/Paste
	{ on = [ "d" ], exec = "delete --cut",                              desc = "剪切选择的字符" },
	{ on = [ "D" ], exec = [ "delete --cut", "move 999" ],              desc = "剪切到行尾" },
	{ on = [ "c" ], exec = "delete --cut --insert",                     desc = "替换选择的字符" },
	{ on = [ "C" ], exec = [ "delete --cut --insert", "move 999" ],     desc = "替换到行尾" },
	{ on = [ "x" ], exec = [ "delete --cut", "move 1 --in-operating" ], desc = "剪切当前字符" },
	{ on = [ "y" ], exec = "yank",           desc = "复制" },
	{ on = [ "p" ], exec = "paste",          desc = "向前粘贴" },
	{ on = [ "P" ], exec = "paste --before", desc = "向后粘贴" },

	# Undo/Redo
	{ on = [ "u" ],     exec = "undo", desc = "撤销" },
	{ on = [ "<C-r>" ], exec = "redo", desc = "恢复" },

	# Help
	{ on = [ "~" ], exec = "help", desc = "打开帮助" }
]

[completion]

keymap = [
	{ on = [ "<C-q>" ], exec = "close",          desc = "取消补全" },
	{ on = [ "<Tab>" ], exec = "close --submit", desc = "确认补全" },

	{ on = [ "<C-p>" ], exec = "arrow -1", desc = "上移一行" },
	{ on = [ "<C-n>" ], exec = "arrow 1",  desc = "下移一行" },

	{ on = [ "<Up>" ],   exec = "arrow -1", desc = "上移一行" },
	{ on = [ "<Down>" ], exec = "arrow 1",  desc = "下移一行" },

	{ on = [ "~" ], exec = "help", desc = "打开帮助" }
]

[help]

keymap = [
	{ on = [ "<Esc>" ], exec = "escape", desc = "清楚过滤或隐藏帮助" },
	{ on = [ "q" ],     exec = "close",  desc = "退出帮助" },
	{ on = [ "<A-q>" ], exec = "close",  desc = "退出帮助" },

	# Navigation
	{ on = [ "k" ], exec = "arrow -1", desc = "上移一行" },
	{ on = [ "j" ], exec = "arrow 1",  desc = "下移一行" },

	{ on = [ "K" ], exec = "arrow -5", desc = "上移五行" },
	{ on = [ "J" ], exec = "arrow 5",  desc = "下移五行" },

	{ on = [ "<Up>" ],   exec = "arrow -1", desc = "上移一行" },
	{ on = [ "<Down>" ], exec = "arrow 1",  desc = "下移一行" },

	{ on = [ "<S-Up>" ],   exec = "arrow -5", desc = "上移五行" },
	{ on = [ "<S-Down>" ], exec = "arrow 5",  desc = "下移五行" },

	# Filtering
	{ on = [ "/" ], exec = "filter", desc = "搜索帮助" },
]
