[config]
version_check = false
fallback_color = "#ffbf9b"
expr_prefix = "{{"
expr_postfix = "}}"
block_prefix = "<*"
block_postfix = "*>"

[config.wallpaper]
set = true
command = "swww"
# command = "caelestia wallpaper -f {{ image }}"


[templates.btop]
input_path = './templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'
post_hook = 'pkill -USR2 btop || true'

[templates.cava]
input_path = './templates/cava-colors.ini'
output_path = '~/.config/cava/themes/matugen'
post_hook = "pkill -USR1 cava"

[templates.fuzzel]
input_path = './templates/fuzzel.ini'
output_path = '~/.config/fuzzel/colors.ini'

[templates.ghostty]
input_path = './templates/ghostty'
output_path = '~/.config/ghostty/themes/Matugen'
post_hook = 'pkill -SIGUSR2 ghostty'

[templates.hyprland]
input_path = './templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'

[templates.kitty]
input_path = './templates/kitty-colors.conf'
output_path = '~/.config/kitty/themes/Matugen.conf'
post_hook = 'kitty +kitten themes --reload-in=all Matugen'

[templates.niri]
input_path = './templates/niri-colors.kdl'
output_path = '~/.config/niri/colors.kdl'
post_hook = 'niri msg action load-config-file'

[templates.rofi]
input_path = './templates/rofi-colors.rasi'
output_path = '~/.config/rofi/colors.rasi'

[templates.waybar]
input_path = './templates/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'

[templates.yazi]
input_path = './templates/yazi-theme.toml'
output_path = '~/.cache/matugen/yazi-theme.toml'

[templates.obs]
input_path = './templates/matugen.obt'
output_path = '~/.config/obs-studio/themes/matugen.obt'
