gui:
  theme:
    activeBorderColor:
      - "#eebebe"
      - bold
    inactiveBorderColor:
      - "#a5adce"
    optionsTextColor:
      - "#8caaee"
    selectedLineBgColor:
      - "#414559"
    cherryPickedCommitBgColor:
      - "#51576d"
    cherryPickedCommitFgColor:
      - "#eebebe"
    unstagedChangesColor:
      - "#e78284"
    defaultFgColor:
      - "#c6d0f5"
    searchingActiveBorderColor:
      - "#e5c890"
  authorColors:
    "*": "#babbf1"
  nerdFontsVersion: "3"
git:
  paging:
    pager: "--dark --paging=never"
  mainBranches:
    - master
    - main
os:
  open: "vi ({filename}) > /dev/null"
  openLink: "firefox ({link})"
