#!/usr/bin/env bash

## Open folders in thunar
FILE="$HOME/.cache/eww_launch.dashboard"
CFG="$HOME/.config/eww/dashboard"
EWW=$(which eww)

close_dash() {
	${EWW} --config "$CFG" close \
		background profile system clock uptime music github \
		reddit twitter bilibili youtube weather apps mail logout sleep reboot poweroff folders
	rm -rf "$FILE"
}

if [[ "$1" == "--dl" ]]; then
	close_dash && thunar ~/下载 &

elif [[ "$1" == "--docs" ]]; then
	close_dash && thunar ~/文档 &

elif [[ "$1" == "--music" ]]; then
	close_dash && thunar /media/数据/音乐 &

elif [[ "$1" == "--pics" ]]; then
	close_dash && thunar ~/图片 &

elif [[ "$1" == "--cfg" ]]; then
	close_dash && thunar ~/.config &

elif [[ "$1" == "--local" ]]; then
	close_dash && thunar ~/.local/share &

fi
