[manager]

prepend_keymap = [
    { on = [
        "B",
    ], run = "plugin hexyl", desc = "二进制显示" },
    { on = [
        "C",
    ], run = "plugin ouch --args=zip", desc = "压缩文件" },
    { on = [
        "E",
    ], run = "plugin eza-preview", desc = "目录预览切换(tree/list)" },
    { on = "T", run = "plugin toggle-pane max-preview", desc = "最大化或恢复预览窗口" },
    { on = "M", run = "plugin mount", desc = "挂载磁盘" },

    # glow.yazi
    { on = [
        "<C-e>",
    ], run = "seek 5" },
    { on = [
        "<C-y>",
    ], run = "seek -5" },

    # fuse挂载压缩文件
    { on = [
        "<Right>",
    ], run = "plugin fuse-archive --args=mount", desc = "进入或者挂载压缩文件" },
    { on = [
        "<Left>",
    ], run = "plugin fuse-archive --args=unmount", desc = "离开或者卸载压缩文件" },

]

keymap = [
    # 显示信息
    { on = "<Tab>", run = "spot", desc = "显示当前文件信息" },

    # 退出
    { on = [
        "<Esc>",
    ], run = "escape", desc = "退出visual模式, 清除选择, 取消搜索" },
    { on = [
        "q",
    ], run = "quit", desc = "退出" },
    { on = [
        "Q",
    ], run = "quit --no-cwd-file", desc = "强制退出，不保存修改" },
    { on = [
        "<C-w>",
    ], run = "close", desc = "关闭当前标签，如果是最后一个标签则退出" },
    { on = [
        "<C-z>",
    ], run = "suspend", desc = "暂停" },

    # 定位
    { on = [
        "k",
    ], run = "arrow -1", desc = "向上移动一行" },
    { on = [
        "j",
    ], run = "arrow 1", desc = "向下移动一行" },

    { on = [
        "K",
    ], run = "arrow -5", desc = "向上移动5行" },
    { on = [
        "J",
    ], run = "arrow 5", desc = "向下移动5行" },

    { on = [
        "h",
    ], run = [
        "leave",
        "escape --visual --select",
    ], desc = "进入上层目录" },
    { on = [
        "l",
    ], run = [
        "enter",
        "escape --visual --select",
    ], desc = "进入子目录" },

    { on = [
        "H",
    ], run = "back", desc = "返回上一个目录" },
    { on = [
        "L",
    ], run = "forward", desc = "进入下一个目录" },

    { on = [
        "<Up>",
    ], run = "arrow -1", desc = "向上移动一行" },
    { on = [
        "<Down>",
    ], run = "arrow 1", desc = "向下移动一行" },
    { on = [
        "<Left>",
    ], run = "leave", desc = "进入上层目" },
    { on = [
        "<Right>",
    ], run = "enter", desc = "进入子目录" },

    { on = [
        "g",
        "g",
    ], run = "arrow top", desc = "移动到顶部" },
    { on = [
        "G",
    ], run = "arrow bot", desc = "移动到底部" },

    { on = [
        "<S-Up>",
    ], run = "arrow -5", desc = "向上移动5行" },
    { on = [
        "<S-Down>",
    ], run = "arrow 5", desc = "向下移动5行" },

    { on = [
        "<C-u>",
    ], run = "arrow -50%", desc = "向上移动半屏" },
    { on = [
        "<C-d>",
    ], run = "arrow 50%", desc = "向下移动半屏" },
    { on = [
        "<C-b>",
    ], run = "arrow -100%", desc = "向上移动整屏" },
    { on = [
        "<C-f>",
    ], run = "arrow 100%", desc = "向下移动整屏" },

    { on = [
        "<C-PageUp>",
    ], run = "arrow -50%", desc = "向上移动半屏" },
    { on = [
        "<C-PageDown>",
    ], run = "arrow 50%", desc = "向下移动半屏" },
    { on = [
        "<PageUp>",
    ], run = "arrow -100%", desc = "向上移动整屏" },
    { on = [
        "<PageDown>",
    ], run = "arrow 100%", desc = "向下移动整屏" },

    { on = [
        "<A-k>",
    ], run = "seek -5", desc = "Seek up 5 units in the preview" },
    { on = [
        "<A-j>",
    ], run = "seek 5", desc = "Seek down 5 units in the preview" },
    { on = [
        "<A-PageUp>",
    ], run = "seek -5", desc = "Seek up 5 units in the preview" },
    { on = [
        "<A-PageDown>",
    ], run = "seek 5", desc = "Seek down 5 units in the preview" },

    # 选择
    { on = [
        "<Space>",
    ], run = [
        "select --state=none",
        "arrow 1",
    ], desc = "切换选择状态" },
    { on = [
        "v",
    ], run = "visual_mode", desc = "进入visual模式" },
    { on = [
        "V",
    ], run = "visual_mode --unset", desc = "退出visual模式(unset mode)" },
    { on = [
        "<C-a>",
    ], run = "select_all --state=true", desc = "全选" },
    { on = [
        "<C-r>",
    ], run = "select_all --state=none", desc = "打开/取消全选" },

    # 操作
    { on = [
        "o",
    ], run = "open", desc = "打开选择的文件" },
    { on = [
        "O",
    ], run = "open --interactive", desc = "交互式打开选择的文件" },
    { on = [
        "<Enter>",
    ], run = "open", desc = "打开选择的文件" },
    { on = [
        "<C-Enter>",
    ], run = "open --interactive", desc = "交互式打开选择的文件" },
    { on = [
        "y",
    ], run = [
        "yank",
        "escape --visual --select",
    ], desc = "复制选择的文件" },
    { on = [
        "x",
    ], run = [
        "yank --cut",
        "escape --visual --select",
    ], desc = "剪切选择的文件" },
    { on = [
        "p",
    ], run = "paste", desc = "粘贴选择的文件" },
    { on = [
        "P",
    ], run = "paste --force", desc = "粘贴选择的文件(如果文件存在则覆盖文件)" },
    { on = [
        "-",
    ], run = "link", desc = "Symlink the absolute path of files" },
    { on = [
        "_",
    ], run = "link --relative", desc = "Symlink the relative path of files" },
    { on = [
        "d",
    ], run = [
        "remove",
        "escape --visual --select",
    ], desc = "移动到回收站" },
    { on = [
        "D",
    ], run = [
        "remove --permanently",
        "escape --visual --select",
    ], desc = "永久删除" },
    { on = [
        "a",
    ], run = "create", desc = "新建文件或目录(新建目录需要以/结尾)" },
    { on = [
        "r",
    ], run = "rename", desc = "重命名文件或目录" },
    { on = [
        ";",
    ], run = "shell --interactive", desc = "运行shell命令" },
    { on = [
        ":",
    ], run = "shell --block --interactive", desc = "运行shell命令(冻结UI直到命令完成)" },
    { on = [
        ".",
    ], run = "hidden toggle", desc = "显示隐藏文件" },
    { on = [
        "s",
    ], run = "search fd", desc = "名字搜索，使用fd做后端" },
    { on = [
        "S",
    ], run = "search rg", desc = "搜索文件内容, 使用ripgrep做后端" },
    { on = [
        "<C-s>",
    ], run = "search none", desc = "取消正在进行的搜索" },
    { on = [
        "Z",
    ], run = "plugin zoxide", desc = "切换目录, 使用zoxide做后端" },
    { on = [
        "z",
    ], run = "plugin fzf", desc = "切换目录或定位文件, 使用fzf做后端" },

    # Linemode
    { on = [
        "m",
        "b",
    ], run = "linemode btime", desc = "Set linemode to btime" },
    { on = [
        "m",
        "m",
    ], run = "linemode mtime", desc = "Set linemode to mtime" },
    { on = [
        "m",
        "n",
    ], run = "linemode none", desc = "Set linemode to none" },
    { on = [
        "m",
        "o",
    ], run = "linemode owner", desc = "Set linemode to owner" },
    { on = [
        "m",
        "p",
    ], run = "linemode permissions", desc = "Set linemode to permissions" },
    { on = [
        "m",
        "s",
    ], run = "linemode size", desc = "Set linemode to size" },

    # 复制
    { on = [
        "c",
        "c",
    ], run = "copy path", desc = "复制绝对路径" },
    { on = [
        "c",
        "d",
    ], run = "copy dirname", desc = "复制父目录路径" },
    { on = [
        "c",
        "f",
    ], run = "copy filename", desc = "复制文件名" },
    { on = [
        "c",
        "n",
    ], run = "copy name_without_ext", desc = "复制文件名, 不包括扩展名" },

    # 过滤
    { on = [
        "f",
    ], run = "filter --smart", desc = "过滤文件" },

    # 查找
    { on = [
        "/",
    ], run = "find --smart", desc = "向前搜索文件" },
    { on = [
        "?",
    ], run = "find --previous --smart", desc = "向后搜索文件" },
    { on = [
        "n",
    ], run = "find_arrow", desc = "搜索下一个" },
    { on = [
        "N",
    ], run = "find_arrow --previous", desc = "搜索上一个" },

    # 文件管理
    { on = [
        ",",
        "m",
    ], run = "sort mtime --reverse=no --dir-first=yes", desc = "按修改时间排序" },
    { on = [
        ",",
        "M",
    ], run = "sort modified --reverse --dir-first=yes", desc = "按修改时间排序(降序)" },
    { on = [
        ",",
        "c",
    ], run = "sort btime --reverse=no --dir-first=yes", desc = "按创建时间排序" },
    { on = [
        ",",
        "C",
    ], run = "sort btime  --reverse --dir-first=yes", desc = "按创建时间排序(降序)" },
    { on = [
        ",",
        "e",
    ], run = "sort extension --reverse=no --dir-first=yes", desc = "按扩展名排序" },
    { on = [
        ",",
        "E",
    ], run = "sort extension --reverse --dir-first=yes", desc = "按扩展名排序(降序)" },
    { on = [
        ",",
        "a",
    ], run = "sort alphabetical --reverse=no --dir-first=yes", desc = "按字母排序" },
    { on = [
        ",",
        "A",
    ], run = "sort alphabetical --reverse --dir-first=yes", desc = "按字母排序(降序)" },
    { on = [
        ",",
        "n",
    ], run = "sort natural --reverse=no --dir-first=yes", desc = "自然排序" },
    { on = [
        ",",
        "N",
    ], run = "sort natural --reverse --dir-first=yes", desc = "自然排序(降序)" },
    { on = [
        ",",
        "s",
    ], run = "sort size --reverse=no --dir-first=yes", desc = "按文件大小排序" },
    { on = [
        ",",
        "S",
    ], run = "sort size --reverse --dir-first=yes", desc = "按文件大小排序 (降序)" },
    { on = [
        ",",
        "r",
    ], run = "sort random --reverse=no", desc = "随机排序" },

    # 标签管理
    { on = [
        "t",
    ], run = "tab_create --current", desc = "新建标签" },
    { on = [
        "<S-t>",
    ], run = "tab_close", desc = "关闭标签" },

    { on = [
        "1",
    ], run = "tab_switch 0", desc = "切换到第1个标签" },
    { on = [
        "2",
    ], run = "tab_switch 1", desc = "切换到第2个标签" },
    { on = [
        "3",
    ], run = "tab_switch 2", desc = "切换到第3个标签" },
    { on = [
        "4",
    ], run = "tab_switch 3", desc = "切换到第4个标签" },
    { on = [
        "5",
    ], run = "tab_switch 4", desc = "切换到第5个标签" },
    { on = [
        "6",
    ], run = "tab_switch 5", desc = "切换到第6个标签" },
    { on = [
        "7",
    ], run = "tab_switch 6", desc = "切换到第7个标签" },
    { on = [
        "8",
    ], run = "tab_switch 7", desc = "切换到第8个标签" },
    { on = [
        "9",
    ], run = "tab_switch 8", desc = "切换到第9个标签" },

    { on = [
        "[",
    ], run = "tab_switch -1 --relative", desc = "切换到前一个标签" },
    { on = [
        "]",
    ], run = "tab_switch 1 --relative", desc = "切换到下一个个标签" },

    { on = [
        "{",
    ], run = "tab_swap -1", desc = "与前一个标签交换位置" },
    { on = [
        "}",
    ], run = "tab_swap 1", desc = "与后一个标签交换位置" },

    # 任务管理
    { on = [
        "w",
    ], run = "tasks_show", desc = "显示任务管理器" },

    # 切换目录
    { on = [
        "g",
        "c",
    ], run = "cd ~/.config", desc = "进入config目录" },
    { on = [
        "g",
        "d",
    ], run = "cd ~/下载", desc = "进入下载目录" },
    { on = [
        "g",
        "D",
    ], run = "cd ~/文档", desc = "进入文档目录" },
    { on = [
        "g",
        "e",
    ], run = "cd ~/桌面", desc = "进入桌面目录" },
    { on = [
        "g",
        "h",
    ], run = "cd ~", desc = "进入HOME目录" },
    { on = [
        "g",
        "M",
    ], run = "cd ~/音乐", desc = "进入音乐目录" },
    { on = [
        "g",
        "m",
    ], run = "cd /media/数据/音乐/", desc = "进入音乐目录" },
    { on = [
        "g",
        "p",
    ], run = "cd ~/图片", desc = "进入图片目录" },
    { on = [
        "g",
        "s",
    ], run = "cd ~/.dotfiles", desc = "进入config目录" },
    { on = [
        "g",
        "t",
    ], run = "cd /tmp", desc = "进入tmp目录" },
    { on = [
        "g",
        "v",
    ], run = "cd ~/视频", desc = "进入视频目录" },
    { on = [
        "g",
        "w",
    ], run = "cd ~/图片/Wallpapers", desc = "进入壁纸目录" },
    { on = [
        "g",
        "<Space>",
    ], run = "cd --interactive", desc = "请输入想要进入的目录" },


    # 帮助
    { on = [
        "~",
    ], run = "help", desc = "打开帮助" },
    { on = [
        "<F1>",
    ], run = "help", desc = "打开帮助" },
]


[tasks]

keymap = [
    { on = [
        "<Esc>",
    ], run = "close", desc = "隐藏任务管理器" },
    { on = [
        "w",
    ], run = "close", desc = "隐藏任务管理器" },

    { on = [
        "k",
    ], run = "arrow -1", desc = "向上移动一行" },
    { on = [
        "j",
    ], run = "arrow 1", desc = "向下移动一行" },

    { on = [
        "<Up>",
    ], run = "arrow -1", desc = "向上移动一行" },
    { on = [
        "<Down>",
    ], run = "arrow 1", desc = "向下移动一行" },

    { on = [
        "<Enter>",
    ], run = "inspect", desc = "检查任务" },
    { on = [
        "x",
    ], run = "cancel", desc = "取消任务" },

    { on = [
        "~",
    ], run = "help", desc = "打开帮助" },
    { on = [
        "<F1>",
    ], run = "help", desc = "打开帮助" },
]


[spot]

keymap = [
    { on = "<Esc>", run = "close", desc = "关闭spot" },
    { on = "<C-[>", run = "close", desc = "关闭spot" },
    { on = "<C-c>", run = "close", desc = "关闭spot" },
    { on = "<Tab>", run = "close", desc = "关闭spot" },

    { on = "k", run = "arrow -1", desc = "向上移动一行" },
    { on = "j", run = "arrow 1", desc = "向下移动一行" },
    { on = "h", run = "swipe -1", desc = "滑动到下一个文件" },
    { on = "l", run = "swipe 1", desc = "滑动到上一个文件" },

    { on = "<Up>", run = "arrow -1", desc = "向上移动一行" },
    { on = "<Down>", run = "arrow 1", desc = "向下移动一行" },
    { on = "<Left>", run = "swipe -1", desc = "滑动到下一个文件" },
    { on = "<Right>", run = "swipe 1", desc = "滑动到上一个文件" },

    # Copy
    { on = ["c", "c"], run = "copy cell", desc = "复制选择的单元格" },

    # Help
    { on = "~", run = "help", desc = "打开帮助" },
    { on = "<F1>", run = "help", desc = "打开帮助" },
]


[pick]

keymap = [
    { on = [
        "<C-[>",
    ], run = "close", desc = "取消选择" },
    { on = [
        "<C-c>",
    ], run = "close", desc = "取消选择" },
    { on = [
        "<Esc>",
    ], run = "close", desc = "取消选择" },
    { on = [
        "<Enter>",
    ], run = "close --submit", desc = "提交选择" },

    { on = [
        "k",
    ], run = "arrow -1", desc = "向上移动一行" },
    { on = [
        "j",
    ], run = "arrow 1", desc = "向下移动一行" },

    { on = [
        "<Up>",
    ], run = "arrow -1", desc = "向上移动一行" },
    { on = [
        "<Down>",
    ], run = "arrow 1", desc = "向下移动一行" },

    { on = [
        "~",
    ], run = "help", desc = "打开帮助" },
    { on = [
        "<F1>",
    ], run = "help", desc = "打开帮助" },
]


[input]

keymap = [
    { on = [
        "<C-[>",
    ], run = "close", desc = "取消输入" },
    { on = [
        "<C-c>",
    ], run = "close", desc = "取消输入" },
    { on = [
        "<Enter>",
    ], run = "close --submit", desc = "提交输入" },
    { on = [
        "<Esc>",
    ], run = "escape", desc = "回退normal模式, 或者取消输入" },

    # Mode
    { on = [
        "i",
    ], run = "insert", desc = "进入insert模式" },
    { on = [
        "a",
    ], run = "insert --append", desc = "进入append模式" },
    { on = [
        "I",
    ], run = [
        "move -999999",
        "insert",
    ], desc = "进入insert模式, 并移动到文件顶部" },
    { on = [
        "A",
    ], run = [
        "move 999999",
        "insert --append",
    ], desc = "进入append模式, 并移动到文件底部" },
    { on = [
        "v",
    ], run = "visual", desc = "进入visual模式" },
    { on = [
        "V",
    ], run = [
        "move -999999",
        "visual",
        "move 999",
    ], desc = "进入visual模式并全选" },

    # Character-wise movement
    { on = [
        "h",
    ], run = "move -1", desc = "向后移动一个字符" },
    { on = [
        "l",
    ], run = "move 1", desc = "向前移动一个字符" },
    { on = [
        "<Left>",
    ], run = "move -1", desc = "向后移动一个字符" },
    { on = [
        "<Right>",
    ], run = "move 1", desc = "向前移动一个字符" },
    { on = [
        "<C-b>",
    ], run = "move -1", desc = "向后移动一个字符" },
    { on = [
        "<C-f>",
    ], run = "move 1", desc = "向前移动一个字符" },

    # Word-wise movement
    { on = [
        "b",
    ], run = "backward", desc = "向后移动一个单词" },
    { on = [
        "w",
    ], run = "forward", desc = "向前移动一个单词" },
    { on = [
        "e",
    ], run = "forward --end-of-word", desc = "向前移动一个单词" },
    { on = [
        "<A-b>",
    ], run = "backward", desc = "向后移动一个单词" },
    { on = [
        "<A-f>",
    ], run = "forward --end-of-word", desc = "向前移动一个单词" },

    # Line-wise movement
    { on = [
        "0",
    ], run = "move -999", desc = "移动到行首" },
    { on = [
        "$",
    ], run = "move 999", desc = "移动到行尾" },
    { on = [
        "<C-a>",
    ], run = "move -999", desc = "移动到行首" },
    { on = [
        "<C-e>",
    ], run = "move 999", desc = "移动到行尾" },
    { on = [
        "<Home>",
    ], run = "move -999", desc = "移动到行首" },
    { on = [
        "<End>",
    ], run = "move 999", desc = "移动到行尾" },

    # Delete
    { on = [
        "<Backspace>",
    ], run = "backspace", desc = "向后删除一个字符" },
    { on = [
        "<Delete>",
    ], run = "backspace --under", desc = "删除光标处字符" },
    { on = [
        "<C-h>",
    ], run = "backspace", desc = "向后删除一个字符" },
    { on = [
        "<C-d>",
    ], run = "backspace --under", desc = "删除光标处字符" },

    # Kill
    { on = [
        "<C-u>",
    ], run = "kill bol", desc = "删除到行首" },
    { on = [
        "<C-k>",
    ], run = "kill eol", desc = "删除到行尾" },
    { on = [
        "<C-w>",
    ], run = "kill backward", desc = "删除到单词开始" },
    { on = [
        "<A-d>",
    ], run = "kill forward", desc = "删除到单词结尾" },

    # Cut/Yank/Paste
    { on = [
        "d",
    ], run = "delete --cut", desc = "剪切选择的字符" },
    { on = [
        "D",
    ], run = [
        "delete --cut",
        "move 999",
    ], desc = "剪切到行尾" },
    { on = [
        "c",
    ], run = "delete --cut --insert", desc = "替换选择的字符" },
    { on = [
        "C",
    ], run = [
        "delete --cut --insert",
        "move 999",
    ], desc = "替换到行尾" },
    { on = [
        "x",
    ], run = [
        "delete --cut",
        "move 1 --in-operating",
    ], desc = "剪切当前字符" },
    { on = [
        "y",
    ], run = "yank", desc = "复制" },
    { on = [
        "p",
    ], run = "paste", desc = "向前粘贴" },
    { on = [
        "P",
    ], run = "paste --before", desc = "向后粘贴" },

    # 重做和撤销	
    { on = [
        "u",
    ], run = "undo", desc = "撤销" },
    { on = [
        "<C-r>",
    ], run = "redo", desc = "恢复" },

    # 帮助
    { on = [
        "~",
    ], run = "help", desc = "打开帮助" },
    { on = [
        "<F1>",
    ], run = "help", desc = "打开帮助" },
]


[confirm]

keymap = [
    { on = "<Esc>", run = "close", desc = "取消确认" },
    { on = "<C-[>", run = "close", desc = "取消确认" },
    { on = "<C-c>", run = "close", desc = "取消确认" },
    { on = "<Enter>", run = "close --submit", desc = "提交确认" },

    { on = "n", run = "close", desc = "取消确认" },
    { on = "y", run = "close --submit", desc = "提交确认" },

    { on = "k", run = "arrow -1", desc = "上移一行" },
    { on = "j", run = "arrow 1", desc = "下移一行" },

    { on = "<Up>", run = "arrow -1", desc = "上移一行" },
    { on = "<Down>", run = "arrow 1", desc = "下移一行" },

    { on = [
        "~",
    ], run = "help", desc = "打开帮助" },
    { on = [
        "<F1>",
    ], run = "help", desc = "打开帮助" },
]


[completion]

keymap = [
    { on = [
        "<C-c>",
    ], run = "close", desc = "取消补全" },
    { on = [
        "<Tab>",
    ], run = "close --submit", desc = "确认补全" },
    { on = "<Enter>", run = [
        "close --submit",
        "close_input --submit",
    ], desc = "确认补全和输入" },

    { on = [
        "<C-p>",
    ], run = "arrow -1", desc = "上移一行" },
    { on = [
        "<C-n>",
    ], run = "arrow 1", desc = "下移一行" },
    { on = [
        "<Up>",
    ], run = "arrow -1", desc = "上移一行" },
    { on = [
        "<Down>",
    ], run = "arrow 1", desc = "下移一行" },

    { on = [
        "~",
    ], run = "help", desc = "打开帮助" },
    { on = [
        "<F1>",
    ], run = "help", desc = "打开帮助" },
]


[help]

keymap = [
    { on = ["<Esc>"], run = "escape", desc = "清除过滤或隐藏帮助" },
    { on = ["q"], run = "close", desc = "退出帮助" },
    { on = ["<A-q>"], run = "close", desc = "退出帮助" },

    # Navigation
    { on = ["k"], run = "arrow -1", desc = "上移一行" },
    { on = ["j"], run = "arrow 1", desc = "下移一行" },

    { on = ["K"], run = "arrow -5", desc = "上移五行" },
    { on = ["J"], run = "arrow 5", desc = "下移五行" },

    { on = ["<Up>"], run = "arrow -1", desc = "上移一行" },
    { on = ["<Down>"], run = "arrow 1", desc = "下移一行" },

    { on = ["<S-Up>"], run = "arrow -5", desc = "上移五行" },
    { on = ["<S-Down>"], run = "arrow 5", desc = "下移五行" },

    { on = ["/"], run = "filter", desc = "搜索帮助" },
]
