[flavor]
# use = "nightfly"
# use = "rose-pine"
# use = "ls-colors"
# use = "ayu-dark"
# use = "everforest-medium"
# use = "onedark"
# use = "catppuccin-frappe"
# use = "catppuccin-latte"
# use = "catppuccin-mocha"
# use = "catppuccin-macchiato"
# use = "gruvbox-dark"
# use = "kanagawa"
use = "sunset"
# use = "tokyo-night"
# use = "monokai-vibrant"
# use = "crystal"
# use = "nightfly"
