[flavor]
# use = "nightfly"
# use = "ls-colors"
# use = "ayu-dark"
# use = "everforest-medium"
# use = "onedark"
# use = "catppuccin-frappe"
# use = "catppuccin-latte"
# use = "catppuccin-mocha"
# use = "catppuccin-macchiato"
# use = "gruvbox-dark"
# use = "kanagawa"
# use = "sunset"
# use = "monokai-vibrant"
# use = "crystal"
# dark = "ls-colors"
# light = "catppuccin-latte"
# dark = "catppuccin-mocha"
# light = "catppuccin-mocha"
# dark = "everforest-medium"
# light = "everforest-medium"
# dark = "gruvbox-dark"
# light = "gruvbox-dark"
# dark = "kanagawa"
# light = "kanagawa"
light = "kanagawa-lotus"
dark = "kanagawa-dragon"
# dark = "timu-macos-dark"
# light = "timu-macos-light"
# dark = "vscode-dark-modern"
# light = "vscode-light-modern"
# dark = "sunset"
# light = "sunset"
# dark = "tokyo-night"
# light = "tokyo-night"
# dark = "monokai-vibrant"
# light = "monokai-vibrant"
# dark = "crystal"
# light = "crystal"
# dark = "nightfly"
# light = "nightfly"
# dark = "ls-colors"
# light = "ls-colors"
# dark = "ayu-dark"
# light = "ayu-dark"
# dark = "tokyo-night"
# dark = "flexoki-dark"
# light = "flexoki-light"
[tabs]
active = { fg = "#24273a", bg = "#8aadf4", bold = true }
inactive = { fg = "#8aadf4", bg = "#363a4f" }
