local hl = vim.api.nvim_set_hl
hl(0, "FlashBackdrop", { fg = "#6c7086", bold = true })
hl(0, "FlashMatch", { fg = "#3271ae", bold = true, italic = true })
hl(0, "FlashCurrent", { fg = "#04a5e5", bold = true, italic = true, underline = true })
hl(0, "FlashLabel", { fg = "#ff007c", bold = true })
hl(0, "FlashCursor", { fg = "#bf9c46", bold = true })
hl(0, "FlashPrompt", { fg = "#e5a84b", italic = true, bold = true })
hl(0, "FlashPromptIcon", { fg = "#c35c5d", italic = true })
-- hop.nvim
hl(0, "HopUnmatched", { fg = "#94a9b8", bold = true })
hl(0, "HopCursor", { fg = "#f29a76", bold = true })
hl(0, "HopPreview", { fg = "#a99f70", bold = true })
hl(0, "HopNextKey", { fg = "#ff007c", bold = true })
hl(0, "HopNextKey1", { fg = "#b7c741", bold = true })
hl(0, "HopNextKey2", { fg = "#b7c742", bold = true })
-- snack indent
hl(0, "SnacksIndent1", { fg = "#E06C75", bold = true })
hl(0, "SnacksIndent2", { fg = "#E5C07B", bold = true })
hl(0, "SnacksIndent3", { fg = "#61AFEF", bold = true })
hl(0, "SnacksIndent4", { fg = "#D19A66", bold = true })
hl(0, "SnacksIndent5", { fg = "#98C379", bold = true })
hl(0, "SnacksIndent6", { fg = "#C678DD", bold = true })
hl(0, "SnacksIndent7", { fg = "#56B6C2", bold = true })
hl(0, "SnacksIndent8", { fg = "#9d8a21", bold = true })
hl(0, "SnacksIndentScope", { fg = "#b32142", bold = true })
hl(0, "SnacksIndentChunk", { fg = "#b7c741", bold = true })
