$image = /home/xujian/图片/Wallpapers/元瑶59.jpg

$background = rgba(19120dff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(382e29ff)

$inverse_primary = rgba(8b4f25ff)

$inverse_surface = rgba(f0dfd7ff)

$on_background = rgba(f0dfd7ff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(512400ff)

$on_primary_container = rgba(ffdbc7ff)

$on_primary_fixed = rgba(311300ff)

$on_primary_fixed_variant = rgba(6e380fff)

$on_secondary = rgba(432b1cff)

$on_secondary_container = rgba(ffdbc7ff)

$on_secondary_fixed = rgba(2b1709ff)

$on_secondary_fixed_variant = rgba(5b4130ff)

$on_surface = rgba(f0dfd7ff)

$on_surface_variant = rgba(d7c3b8ff)

$on_tertiary = rgba(32320aff)

$on_tertiary_container = rgba(e7e6adff)

$on_tertiary_fixed = rgba(1c1d00ff)

$on_tertiary_fixed_variant = rgba(48491eff)

$outline = rgba(9f8d83ff)

$outline_variant = rgba(52443cff)

$primary = rgba(ffb688ff)

$primary_container = rgba(6e380fff)

$primary_fixed = rgba(ffdbc7ff)

$primary_fixed_dim = rgba(ffb688ff)

$scrim = rgba(000000ff)

$secondary = rgba(e5bfa9ff)

$secondary_container = rgba(5b4130ff)

$secondary_fixed = rgba(ffdbc7ff)

$secondary_fixed_dim = rgba(e5bfa9ff)

$shadow = rgba(000000ff)

$source_color = rgba(8d4f22ff)

$surface = rgba(19120dff)

$surface_bright = rgba(413731ff)

$surface_container = rgba(261e19ff)

$surface_container_high = rgba(312823ff)

$surface_container_highest = rgba(3d332dff)

$surface_container_low = rgba(221a15ff)

$surface_container_lowest = rgba(140d08ff)

$surface_dim = rgba(19120dff)

$surface_tint = rgba(ffb688ff)

$surface_variant = rgba(52443cff)

$tertiary = rgba(caca93ff)

$tertiary_container = rgba(48491eff)

$tertiary_fixed = rgba(e7e6adff)

$tertiary_fixed_dim = rgba(caca93ff)

