# █░░ ▄▀█ █▄█ █▀█ █░█ ▀█▀ █▀
# █▄▄ █▀█ ░█░ █▄█ █▄█ ░█░ ▄█

# default_split_ratio = 0.1-1.9 定义新窗口比例，数字越小新窗口越大,
# 默认为1,新旧窗口一样大

dwindle {
    # pseudotile = true # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # you probably want this
    force_split = 2
    default_split_ratio = 0.9
    split_bias = 1
}

# orientation = right|left|top|bottom|center
master {
    orientation = right
    new_on_top = true
    mfact = 0.70
    orientation = center
    # always_center_master = true
    slave_count_for_center_master = 2
}

# 类niri模式
scrolling {
    fullscreen_on_one_column = true
    column_width = 0.5
    focus_fit_method = 1
    follow_focus =true
    follow_min_visible = 0.4
    explicit_column_widths = 0.333, 0.5, 0.667, 1.0
    direction = right
}
general {
    layout = dwindle
    # layout = master
    # layout = hy3
    # layout = scrolling
    locale = zh_CN
}
