return {
  "onsails/lspkind.nvim",
  opts = function(_, opts)
    opts.preset = "codicons"
    opts.mode = "symbol_text"
    opts.symbol_map = {
      Array = "󰅪",
      Boolean = "⊨",
      Class = "󰠱",
      Color = "󰏘",
      Constant = "󰏿",
      Constructor = "",
      Event = "",
      Enum = "",
      EnumMember = "",
      Function = "󰊕",
      File = "󰈙",
      Field = "󰇽",
      Folder = "󰉋",
      Interface = "",
      Key = "󰌆",
      Keyword = "󰌋",
      Method = "󰆧",
      Module = "",
      Namespace = "󰅪",
      Number = "#",
      Null = "",
      Object = "",
      -- Object = "󰀚",
      Operator = "󰆕",
      Package = "󰏗",
      Property = "",
      Reference = "",
      Snippet = "",
      -- String = "",
      String = "󰀬",
      TypeParameter = "󰊄",
      Struct = "",
      Text = "",
      -- Variable = "󰀫",
      -- Variable = "󰂡",
      Variable = "",
      Unit = "",
      Value = "󰎠",
    }
    return opts
  end,
}
