import = [
    "~/.config/alacritty/themes/one_dark.toml",
    "~/.config/alacritty/keybindings.toml",
]
live_config_reload = true
# working_directory = "D:/programs"

[colors]
draw_bold_text_with_bright_colors = true
cursor = { text = "#bfe523", cursor = "#bc3823" }
vi_mode_cursor = { text = "#bfe523", cursor = "#bc3823" }

[cursor]
unfocused_hollow = false
vi_mode_style = { shape = "Block", blinking = "Off" }
thickness = 0.15

[cursor.style]
blinking = "Always"
shape = "Underline"

[env]
TERM = "alacritty"

[font]
builtin_box_drawing = true
size = 16.0

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
family = "NotoSansM Nerd Font Mono"
style = "Regular"

[scrolling]
history = 100000
multiplier = 6

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[shell]
program = "/usr/bin/bash"

[window]
padding = { x = 3, y = 3 }
dynamic_padding = true
dynamic_title = true
opacity = 0.9
title = "Alacritty"
decorations = "None"
startup_mode = "Maximized"
decorations_theme_variant = "Light"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[bell]
animation = "EaseOutQuint"

[mouse]
hide_when_typing = true
